controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

vue_frontend:
  path: /{vueRouting}
  defaults: { _controller: 'App\Controller\DefaultController::index' }
  requirements:
    vueRouting: .*
